name: GHCR Docker summary

description: Output a step summary for a docker image published to GHCR

inputs:
  repository:
    required: true
    description: Container image name org/image
  tag:
    required: true
    description: Image tag to match
  extra_tags:
    description: Comma-separated list of additional tags to include in the summary
    required: false
    default: ""
  GITHUB_TOKEN:
    description: GitHub token for authentication
    required: true

outputs:
  image_id:
    description: Internal GitHub Packages image ID

runs:
  using: "composite"
  steps:
    - id: get-image-id
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        chmod +x ${{ github.action_path }}/get_image_id.sh
        IMAGE_ID=$(${{ github.action_path }}/get_image_id.sh \
          "${{ inputs.repository }}" \
          "${{ inputs.tag }}")
        echo "Resolved image_id: $IMAGE_ID"
        echo "$IMAGE_ID" >> "$GITHUB_OUTPUT"

    - name: Write Docker Image Summary
      shell: bash
      run: |
        IMAGE="${{ inputs.repository }}"
        TAG="${{ inputs.tag }}"
        IMAGE_NAME="$(basename "$IMAGE")"
        REPO_OWNER="${{ github.repository_owner }}"
        EXTRA_TAGS="${{ inputs.extra_tags }}"

        echo "### 🐳 Docker Image" >> "$GITHUB_STEP_SUMMARY"
        echo "- *$TAG* [registry](https://github.com/orgs/$REPO_OWNER/packages/container/$IMAGE_NAME?tag=$TAG)" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo '```bash' >> "$GITHUB_STEP_SUMMARY"
        echo "docker pull ghcr.io/$IMAGE:$TAG" >> "$GITHUB_STEP_SUMMARY"

        if [[ -n "$EXTRA_TAGS" ]]; then
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "### 🏷️ Additional Tags" >> "$GITHUB_STEP_SUMMARY"
          IFS=',' read -ra TAGS <<< "$EXTRA_TAGS"
          for EXTRA_TAG in "${TAGS[@]}"; do
            echo "- *$EXTRA_TAG* [registry](https://github.com/orgs/$REPO_OWNER/packages/container/$IMAGE_NAME?tag=$EXTRA_TAG)" >> "$GITHUB_STEP_SUMMARY"
            echo "docker pull ghcr.io/$IMAGE:$EXTRA_TAG" >> "$GITHUB_STEP_SUMMARY"
          done
        fi

        echo '```' >> "$GITHUB_STEP_SUMMARY"
