name: "Create Metadata"
description: "Generates standardized image.json metadata file and exposes all values as outputs"

inputs:
  registry:
    description: "Container registry"
    required: false
    default: "ghcr.io"
  GITHUB_TOKEN:
    description: "GitHub token for authentication"
    required: true
  repository:
    description: "Repository name (e.g. org/project). Defaults to github.repository"
    required: false
  tag_prefix:
    description: "Optional prefix for tag (e.g., dev, base)"
    required: false
  version:
    description: "Version or tag (e.g., v1.2.3)"
    required: true
  description:
    description: "Image description"
    required: true
  artifact:
    description: "Name of the output artifact"
    required: false
    default: "image.json"
  is_release:
    description: "Add latest tag to the image"
    required: false
    default: "false"

outputs:
  registry:
    value: ${{ steps.extract.outputs.registry }}
  repository:
    value: ${{ steps.extract.outputs.repository }}
  tag:
    value: ${{ steps.extract.outputs.tag }}
  image:
    value: ${{ steps.extract.outputs.image }}
  url:
    value: ${{ steps.extract.outputs.url }}
  description:
    value: ${{ steps.extract.outputs.description }}
  source:
    value: ${{ steps.extract.outputs.source }}
  version:
    value: ${{ steps.extract.outputs.version }}
  extra_urls:
    value: ${{ steps.extract.outputs.extra_urls }}
  extra_tags:
    value: ${{ steps.extract.outputs.extra_tags }}


runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Dist Tags
      id: dist_tags
      uses: agent-ix/git-actions/get-dist-tags@main
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Compute and write image.json
      id: meta
      shell: bash
      run: |
        REPO="${{ inputs.repository || github.repository }}"
        TAG="${{ inputs.tag_prefix }}${{ inputs.tag_prefix && '-' || '' }}${{ inputs.version }}"
        IMAGE="${{ inputs.registry }}/$REPO"
        URL="$IMAGE:$TAG"
        SOURCE="https://github.com/${{ github.repository }}"

        # convert floating tags to full urls
        FLOATING_URLS=()
        IFS=',' read -ra FLOATING_TAGS <<< "${{ steps.dist_tags.outputs.dist_tags }}"
        for FLOATING_TAG in "${FLOATING_TAGS[@]}"; do
          FLOATING_URLS+=("$IMAGE:$FLOATING_TAG")
        done

        # join floating urls with commas
        FLOATING_URLS=$(IFS=,; echo "${FLOATING_URLS[*]}")

        cat <<EOF > ${{ inputs.artifact }}
        {
          "registry": "${{ inputs.registry }}",
          "repository": "$REPO",
          "tag": "$TAG",
          "image": "$IMAGE",
          "url": "$URL",
          "description": "${{ inputs.description }}",
          "source": "$SOURCE",
          "version": "${{ inputs.version }}",
          "extra_urls": "$FLOATING_URLS",
          "extra_tags": "$FLOATING_TAGS"
        }
        EOF

        echo "Image metadata:"
        jq -r 'to_entries[] | "\(.key)=\(.value)"' "${{ inputs.artifact }}"

    - name: Export all fields as outputs
      id: extract
      shell: bash
      run: |
        jq -r 'to_entries[] | "\(.key)=\(.value)"' "${{ inputs.artifact }}" >> "$GITHUB_OUTPUT"

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: ${{ inputs.artifact }}
